;;; httpbin.el --- A client for the httpbin service  -*- lexical-binding: t; -*-

;; Copyright (C) 2024  Ryan Kaskel

;; Author: Ryan Kaskel <dev@ryankaskel.com>
;; Keywords: tools, data

;; This program is free software; you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation, either version 3 of the License, or
;; (at your option) any later version.

;; This program is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.

;; You should have received a copy of the GNU General Public License
;; along with this program.  If not, see <https://www.gnu.org/licenses/>.

;;; Commentary:

;;

;;; Code:

(require 'url-parse)

(defconst httpbin-api-url "https://httpbin.app.kaskel.net")

(defun httpbin--fetch-json (endpoint)
  "Fetch ENDPOINT from the service and return the parsed JSON
 response"
  (let ((url-show-status nil)
        (url (concat httpbin-api-url endpoint)))
    (with-temp-buffer
      (url-insert-file-contents url )
      (json-parse-buffer))))

(defun httpbin-uuid (&optional print-value)
  "Return a UUID generated by the service."
  (interactive "P")
  (let* ((response (httpbin--fetch-json "/uuid"))
         (uuid (gethash "uuid" response)))
    (when print-value
      (message uuid))
    uuid))

(provide 'httpbin)
;;; httpbin.el ends here
