## author: Ryan Kaskel
## license: GNU GPLv3
## blurb: Powered by Protesilaos Stavrou's emacs themes

background #f2f0e7
foreground #1a3530
cursor #906f20
cursor_text_color #f2f0e7
url_color #103077
active_border_color #6e522a
inactive_border_color #e7e2d7
bell_border_color #595000
selection_foreground #f2f0e7
selection_background #1a3530
macos_titlebar_color background
color0 #1a3530
color8 #6e522a
color1 #982500
color9 #982500
color2 #005700
color10 #005700
color3 #595000
color11 #595000
color4 #103077
color12 #103077
color5 #700054
color13 #700054
color6 #005460
color14 #005460
color7 #e7e2d7
color15 #f2f0e7
