## author: Ryan Kaskel
## license: GNU GPLv3
## blurb: Powered by Protesilaos Stavrou's emacs themes

background #153227
foreground #b9d3b0
cursor #d3b18e
cursor_text_color #153227
url_color #8fbae5
active_border_color #a09f9b
inactive_border_color #303931
bell_border_color #c4b980
selection_foreground #153227
selection_background #b9d3b0
macos_titlebar_color background
color0 #153227
color8 #303931
color1 #e8a27f
color9 #e8a27f
color2 #82cc7f
color10 #82cc7f
color3 #c4b980
color11 #c4b980
color4 #8fbae5
color12 #8fbae5
color5 #e9acbf
color13 #e9acbf
color6 #a0c0d0
color14 #a0c0d0
color7 #a09f9b
color15 #b9d3b0
