## author: Ryan Kaskel
## license: GNU GPLv3
## blurb: Powered by Protesilaos Stavrou's emacs themes

background #000000
foreground #ffffff
cursor #ccaaee
cursor_text_color #000000
url_color #9fbfe7
active_border_color #a2a0b2
inactive_border_color #332d38
bell_border_color #c0b080
selection_foreground #000000
selection_background #ffffff
macos_titlebar_color background
color0 #000000
color8 #332d38
color1 #eca28f
color9 #eca28f
color2 #b9d0aa
color10 #b9d0aa
color3 #c0b080
color11 #c0b080
color4 #9fbfe7
color12 #9fbfe7
color5 #e9acbf
color13 #e9acbf
color6 #a0c0d0
color14 #a0c0d0
color7 #a2a0b2
color15 #ffffff
