## author: Ryan Kaskel
## license: GNU GPLv3
## blurb: Powered by Protesilaos Stavrou's emacs themes

background #f0deab
foreground #402f3e
cursor #000000
cursor_text_color #f0deab
url_color #183172
active_border_color #485027
inactive_border_color #dfce9f
bell_border_color #783400
selection_foreground #f0deab
selection_background #402f3e
macos_titlebar_color background
color0 #402f3e
color8 #485027
color1 #a02600
color9 #a02600
color2 #406900
color10 #406900
color3 #783400
color11 #783400
color4 #183172
color12 #183172
color5 #820145
color13 #820145
color6 #025763
color14 #025763
color7 #dfce9f
color15 #f0deab
