## author: Ryan Kaskel
## license: GNU GPLv3
## blurb: Powered by Protesilaos Stavrou's emacs themes

background #e2f0c9
foreground #25311f
cursor #00a093
cursor_text_color #e2f0c9
url_color #003370
active_border_color #6b5a77
inactive_border_color #d5e1c0
bell_border_color #706000
selection_foreground #e2f0c9
selection_background #25311f
macos_titlebar_color background
color0 #25311f
color8 #6b5a77
color1 #990020
color9 #990020
color2 #006710
color10 #006710
color3 #706000
color11 #706000
color4 #003370
color12 #003370
color5 #782050
color13 #782050
color6 #006070
color14 #006070
color7 #d5e1c0
color15 #e2f0c9
