## author: Ryan Kaskel
## license: GNU GPLv3
## blurb: Powered by Protesilaos Stavrou's emacs themes

background #351b10
foreground #e0baa0
cursor #ef3839
cursor_text_color #351b10
url_color #7fafc7
active_border_color #a0a196
inactive_border_color #48332b
bell_border_color #cfa030
selection_foreground #351b10
selection_background #e0baa0
macos_titlebar_color background
color0 #351b10
color8 #48332b
color1 #fc826f
color9 #fc826f
color2 #b9c06a
color10 #b9c06a
color3 #cfa030
color11 #cfa030
color4 #7fafc7
color12 #7fafc7
color5 #df70af
color13 #df70af
color6 #70a0c0
color14 #70a0c0
color7 #a0a196
color15 #e0baa0
