## author: Ryan Kaskel
## license: GNU GPLv3
## blurb: Powered by Protesilaos Stavrou's emacs themes

background #f0eddf
foreground #30232e
cursor #770000
cursor_text_color #f0eddf
url_color #103060
active_border_color #635650
inactive_border_color #dfdfce
bell_border_color #705200
selection_foreground #f0eddf
selection_background #30232e
macos_titlebar_color background
color0 #30232e
color8 #635650
color1 #a03000
color9 #a03000
color2 #206700
color10 #206700
color3 #705200
color11 #705200
color4 #103060
color12 #103060
color5 #690f44
color13 #690f44
color6 #105f66
color14 #105f66
color7 #dfdfce
color15 #f0eddf
