## author: Ryan Kaskel
## license: GNU GPLv3
## blurb: Powered by Protesilaos Stavrou's emacs themes

background #282420
foreground #f5ceb0
cursor #ef7839
cursor_text_color #282420
selection_foreground #f3ac6f
selection_background #7c362c
macos_titlebar_color background
color0 #000000
color8 #595959
color1 #eca27f
color9 #eca27f
color2 #b9d08a
color10 #b9d08a
color3 #c5ba80
color11 #c5ba80
color4 #9fbfe7
color12 #9fbfe7
color5 #e9acbf
color13 #e9acbf
color6 #a0c0d0
color14 #a0c0d0
color7 #a6a6a6
color15 #ffffff
