## author: Ryan Kaskel
## license: GNU GPLv3
## blurb: Powered by Protesilaos Stavrou's emacs themes

background #383035
foreground #e0d5b7
cursor #94d0eb
cursor_text_color #383035
url_color #9fbfe7
active_border_color #afa497
inactive_border_color #484040
bell_border_color #c0b060
selection_foreground #383035
selection_background #e0d5b7
macos_titlebar_color background
color0 #383035
color8 #484040
color1 #eca28f
color9 #eca28f
color2 #b9d0aa
color10 #b9d0aa
color3 #c0b060
color11 #c0b060
color4 #9fbfe7
color12 #9fbfe7
color5 #e9acbf
color13 #e9acbf
color6 #a0c0d0
color14 #a0c0d0
color7 #afa497
color15 #e0d5b7
