## author: Ryan Kaskel
## license: GNU GPLv3
## blurb: Powered by Protesilaos Stavrou's emacs themes

background #303f2d
foreground #d0e2c8
cursor #c0a27a
cursor_text_color #303f2d
url_color #8fbae5
active_border_color #bcbeaf
inactive_border_color #40503d
bell_border_color #c4b980
selection_foreground #303f2d
selection_background #d0e2c8
macos_titlebar_color background
color0 #303f2d
color8 #40503d
color1 #e8a28f
color9 #e8a28f
color2 #82cc9f
color10 #82cc9f
color3 #c4b980
color11 #c4b980
color4 #8fbae5
color12 #8fbae5
color5 #e9acbf
color13 #e9acbf
color6 #a0c0d0
color14 #a0c0d0
color7 #bcbeaf
color15 #d0e2c8
