## author: Ryan Kaskel
## license: GNU GPLv3
## blurb: Powered by Protesilaos Stavrou's emacs themes

background #eaf0c0
foreground #023f2d
cursor #705060
cursor_text_color #eaf0c0
url_color #103077
active_border_color #60504a
inactive_border_color #e0e2be
bell_border_color #595000
selection_foreground #eaf0c0
selection_background #023f2d
macos_titlebar_color background
color0 #023f2d
color8 #60504a
color1 #982500
color9 #982500
color2 #226700
color10 #226700
color3 #595000
color11 #595000
color4 #103077
color12 #103077
color5 #700054
color13 #700054
color6 #005460
color14 #005460
color7 #e0e2be
color15 #eaf0c0
