## author: Ryan Kaskel
## license: GNU GPLv3
## blurb: Powered by Protesilaos Stavrou's emacs themes

background #d9e0ed
foreground #001020
cursor #2040a0
cursor_text_color #d9e0ed
url_color #103077
active_border_color #3f5569
inactive_border_color #c2d1df
bell_border_color #60400f
selection_foreground #d9e0ed
selection_background #001020
macos_titlebar_color background
color0 #001020
color8 #3f5569
color1 #a01010
color9 #a01010
color2 #106710
color10 #106710
color3 #60400f
color11 #60400f
color4 #103077
color12 #103077
color5 #700d50
color13 #700d50
color6 #005355
color14 #005355
color7 #c2d1df
color15 #d9e0ed
