## author: Ryan Kaskel
## license: GNU GPLv3
## blurb: Powered by Protesilaos Stavrou's emacs themes

background #392716
foreground #f8d48c
cursor #f3cf6f
cursor_text_color #392716
url_color #7fbad0
active_border_color #afaf92
inactive_border_color #403023
bell_border_color #d5ba50
selection_foreground #392716
selection_background #f8d48c
macos_titlebar_color background
color0 #392716
color8 #403023
color1 #ec825f
color9 #ec825f
color2 #89b75a
color10 #89b75a
color3 #d5ba50
color11 #d5ba50
color4 #7fbad0
color12 #7fbad0
color5 #e98cbf
color13 #e98cbf
color6 #68c2ce
color14 #68c2ce
color7 #afaf92
color15 #f8d48c
