## author: Ryan Kaskel
## license: GNU GPLv3
## blurb: Powered by Protesilaos Stavrou's emacs themes

background #383025
foreground #e5daa0
cursor #b7b0cb
cursor_text_color #383025
url_color #a0b0eb
active_border_color #c8b9ad
inactive_border_color #514b44
bell_border_color #b9b56f
selection_foreground #383025
selection_background #e5daa0
macos_titlebar_color background
color0 #383025
color8 #514b44
color1 #e0a47f
color9 #e0a47f
color2 #a0c080
color10 #a0c080
color3 #b9b56f
color11 #b9b56f
color4 #a0b0eb
color12 #a0b0eb
color5 #d2a2c0
color13 #d2a2c0
color6 #9bc3c3
color14 #9bc3c3
color7 #c8b9ad
color15 #e5daa0
