## author: Ryan Kaskel
## license: GNU GPLv3
## blurb: Powered by Protesilaos Stavrou's emacs themes

background #3a2e3f
foreground #eed0c7
cursor #b079ff
cursor_text_color #3a2e3f
url_color #9fbfe7
active_border_color #a690c9
inactive_border_color #42394c
bell_border_color #c0b060
selection_foreground #3a2e3f
selection_background #eed0c7
macos_titlebar_color background
color0 #3a2e3f
color8 #42394c
color1 #eca28f
color9 #eca28f
color2 #a0c0a0
color10 #a0c0a0
color3 #c0b060
color11 #c0b060
color4 #9fbfe7
color12 #9fbfe7
color5 #e9acbf
color13 #e9acbf
color6 #a0c0d0
color14 #a0c0d0
color7 #a690c9
color15 #eed0c7
