## author: Ryan Kaskel
## license: GNU GPLv3
## blurb: Powered by Protesilaos Stavrou's emacs themes

background #44312e
foreground #e7d0bf
cursor #74e0ab
cursor_text_color #44312e
selection_foreground #e2a077
selection_background #7e462c
macos_titlebar_color background
color0 #000000
color8 #595959
color1 #eca28f
color9 #eca28f
color2 #b9d0aa
color2 #b9d0aa
color3 #c0b060
color11 #c0b060
color4 #9fbfe7
color12 #9fbfe7
color5 #e9acbf
color13 #e9acbf
color6 #a0c0d0
color14 #a0c0d0
color7 #a6a6a6
color15 #ffffff
