## author: Ryan Kaskel
## license: GNU GPLv3
## blurb: Powered by Protesilaos Stavrou's emacs themes

background #153227
foreground #b9d3b0
cursor #d3b18e
cursor_text_color #153227
selection_foreground #63c789
selection_background #0c512c
macos_titlebar_color background
color0 #000000
color8 #595959
color1 #e8a27f
color9 #e8a27f
color2 #82cc7f
color2 #82cc7f
color3 #c4b980
color11 #c4b980
color4 #8fbae5
color12 #8fbae5
color5 #e9acbf
color13 #e9acbf
color6 #a0c0d0
color14 #a0c0d0
color7 #a6a6a6
color15 #ffffff
