## author: Ryan Kaskel
## license: GNU GPLv3
## blurb: Powered by Protesilaos Stavrou's emacs themes

background #181818
foreground #e7e7e7
cursor #eeddbb
cursor_text_color #181818
url_color #9fbfe7
active_border_color #969696
inactive_border_color #2f2f2f
bell_border_color #c0b080
selection_foreground #181818
selection_background #e7e7e7
macos_titlebar_color background
color0 #181818
color8 #2f2f2f
color1 #eca28f
color9 #eca28f
color2 #b9d0aa
color10 #b9d0aa
color3 #c0b080
color11 #c0b080
color4 #9fbfe7
color12 #9fbfe7
color5 #e9acbf
color13 #e9acbf
color6 #a0c0d0
color14 #a0c0d0
color7 #969696
color15 #e7e7e7
