## author: Ryan Kaskel
## license: GNU GPLv3
## blurb: Powered by Protesilaos Stavrou's emacs themes

background #fef8ed
foreground #40282e
cursor #902728
cursor_text_color #fef8ed
selection_foreground #206038
selection_background #cce7b4
macos_titlebar_color background
color0 #000000
color8 #595959
color1 #a00040
color9 #a00040
color2 #006730
color2 #006730
color3 #704000
color11 #704000
color4 #203080
color12 #203080
color5 #800060
color13 #800060
color6 #005560
color14 #005560
color7 #a6a6a6
color15 #ffffff
