## author: Ryan Kaskel
## license: GNU GPLv3
## blurb: Powered by Protesilaos Stavrou's emacs themes

background #fcf0e5
foreground #40282e
cursor #205798
cursor_text_color #fcf0e5
url_color #183182
active_border_color #8f5854
inactive_border_color #efe4db
bell_border_color #753800
selection_foreground #fcf0e5
selection_background #40282e
macos_titlebar_color background
color0 #40282e
color8 #8f5854
color1 #a02610
color9 #a02610
color2 #006940
color10 #006940
color3 #753800
color11 #753800
color4 #183182
color12 #183182
color5 #820145
color13 #820145
color6 #025763
color14 #025763
color7 #efe4db
color15 #fcf0e5
