## author: Ryan Kaskel
## license: GNU GPLv3
## blurb: Powered by Protesilaos Stavrou's emacs themes

background #221832
foreground #e2d7e7
cursor #c070d0
cursor_text_color #221832
url_color #9fbfe7
active_border_color #a694b1
inactive_border_color #302f3c
bell_border_color #c0b080
selection_foreground #221832
selection_background #e2d7e7
macos_titlebar_color background
color0 #221832
color8 #302f3c
color1 #eca28f
color9 #eca28f
color2 #b9d0aa
color10 #b9d0aa
color3 #c0b080
color11 #c0b080
color4 #9fbfe7
color12 #9fbfe7
color5 #e9acbf
color13 #e9acbf
color6 #a0c0d0
color14 #a0c0d0
color7 #a694b1
color15 #e2d7e7
