## author: Ryan Kaskel
## license: GNU GPLv3
## blurb: Powered by Protesilaos Stavrou's emacs themes

background #282420
foreground #f5ceb0
cursor #ef7839
cursor_text_color #282420
url_color #a6b9e7
active_border_color #afa497
inactive_border_color #40332b
bell_border_color #ceba80
selection_foreground #282420
selection_background #f5ceb0
macos_titlebar_color background
color0 #282420
color8 #40332b
color1 #eca27f
color9 #eca27f
color2 #b9d08a
color10 #b9d08a
color3 #ceba80
color11 #ceba80
color4 #a6b9e7
color12 #a6b9e7
color5 #e9acbf
color13 #e9acbf
color6 #a0c0c0
color14 #a0c0c0
color7 #afa497
color15 #f5ceb0
