## author: Ryan Kaskel
## license: GNU GPLv3
## blurb: Powered by Protesilaos Stavrou's emacs themes

background #351b10
foreground #e0baa0
cursor #ef3839
cursor_text_color #351b10
selection_foreground #ff9d7e
selection_background #7c301c
macos_titlebar_color background
color0 #000000
color8 #595959
color1 #fc826f
color9 #fc826f
color2 #b9c06a
color2 #b9c06a
color3 #cfa030
color11 #cfa030
color4 #7fafc7
color12 #7fafc7
color5 #df70af
color13 #df70af
color6 #70a0c0
color14 #70a0c0
color7 #a6a6a6
color15 #ffffff
