## author: Ryan Kaskel
## license: GNU GPLv3
## blurb: Powered by Protesilaos Stavrou's emacs themes

background #1a143e
foreground #bfcccf
cursor #baa1ab
cursor_text_color #1a143e
url_color #379cf6
active_border_color #7f8385
inactive_border_color #1a204b
bell_border_color #b5967b
selection_foreground #1a143e
selection_background #bfcccf
macos_titlebar_color background
color0 #1a143e
color8 #1a204b
color1 #ef656a
color9 #f47360
color2 #1fa526
color10 #77b22f
color3 #c48502
color11 #b5967b
color4 #379cf6
color12 #6a88ff
color5 #d590af
color13 #af9ef2
color6 #4fb0cf
color14 #3dc0b0
color7 #7f8385
color15 #bfcccf
