## author: Ryan Kaskel
## license: GNU GPLv3
## blurb: Powered by Protesilaos Stavrou's emacs themes

background #d6e4d3
foreground #40314e
cursor #495080
cursor_text_color #d6e4d3
url_color #113384
active_border_color #646170
inactive_border_color #ced7c8
bell_border_color #775228
selection_foreground #d6e4d3
selection_background #40314e
macos_titlebar_color background
color0 #40314e
color8 #646170
color1 #882000
color9 #9a1500
color2 #206020
color10 #3f7000
color3 #6b4500
color11 #775228
color4 #113384
color12 #3a40a0
color5 #922e7f
color13 #503094
color6 #125a7f
color14 #005070
color7 #ced7c8
color15 #d6e4d3
