## author: Ryan Kaskel
## license: GNU GPLv3
## blurb: Powered by Protesilaos Stavrou's emacs themes

background #111111
foreground #cfdfd5
cursor #35f038
cursor_text_color #111111
url_color #37aff6
active_border_color #808f80
inactive_border_color #222522
bell_border_color #cfc04f
selection_foreground #111111
selection_background #cfdfd5
macos_titlebar_color background
color0 #111111
color8 #222522
color1 #ef6560
color9 #f47360
color2 #3fb83f
color10 #7fc500
color3 #d4aa02
color11 #cfc04f
color4 #37aff6
color12 #78afff
color5 #d38faf
color13 #af9fff
color6 #6fc5ef
color14 #5dc0aa
color7 #808f80
color15 #cfdfd5
