## author: Ryan Kaskel
## license: GNU GPLv3
## blurb: Powered by Protesilaos Stavrou's emacs themes

background #fcf7ef
foreground #242521
cursor #007f00
cursor_text_color #fcf7ef
url_color #375cc6
active_border_color #59786f
inactive_border_color #f0ece0
bell_border_color #a2604f
selection_foreground #fcf7ef
selection_background #242521
macos_titlebar_color background
color0 #242521
color8 #59786f
color1 #9f0d0f
color9 #dd0020
color2 #006f00
color10 #557400
color3 #a7601f
color11 #a2604f
color4 #375cc6
color12 #444fcf
color5 #9a456f
color13 #8448aa
color6 #1f70af
color14 #007a9f
color7 #f0ece0
color15 #fcf7ef
