## author: Ryan Kaskel
## license: GNU GPLv3
## blurb: Powered by Protesilaos Stavrou's emacs themes

background #190a0f
foreground #d3cfcf
cursor #ff5aaf
cursor_text_color #190a0f
url_color #8fa5f6
active_border_color #808898
inactive_border_color #291f26
bell_border_color #f59280
selection_foreground #190a0f
selection_background #d3cfcf
macos_titlebar_color background
color0 #190a0f
color8 #291f26
color1 #ff7359
color9 #ff656f
color2 #60b444
color10 #80b25f
color3 #e5b76f
color11 #f59280
color4 #8fa5f6
color12 #a897ef
color5 #ef80bf
color13 #df7fff
color6 #8fbaef
color14 #8fcfdf
color7 #808898
color15 #d3cfcf
