## author: Ryan Kaskel
## license: GNU GPLv3
## blurb: Powered by Protesilaos Stavrou's emacs themes

background #232025
foreground #efd5c5
cursor #f3c09a
cursor_text_color #232025
url_color #57b0ff
active_border_color #8f8886
inactive_border_color #322f34
bell_border_color #deb07a
selection_foreground #232025
selection_background #efd5c5
macos_titlebar_color background
color0 #232025
color8 #322f34
color1 #ff6f6f
color9 #ff7a5f
color2 #51b04f
color10 #7fce5f
color3 #c0b24f
color11 #deb07a
color4 #57b0ff
color12 #80aadf
color5 #ffaacf
color13 #d0b0ff
color6 #6fb3c0
color14 #65c5a8
color7 #8f8886
color15 #efd5c5
