## author: Ryan Kaskel
## license: GNU GPLv3
## blurb: Powered by Protesilaos Stavrou's emacs themes

background #f5f5ff
foreground #1a1a2f
cursor #0000bb
cursor_text_color #f5f5ff
url_color #375cd8
active_border_color #70627f
inactive_border_color #e8e8ea
bell_border_color #765040
selection_foreground #f5f5ff
selection_background #1a1a2f
macos_titlebar_color background
color0 #1a1a2f
color8 #70627f
color1 #d3303a
color9 #e00033
color2 #217a3c
color10 #4a7d00
color3 #805d00
color11 #765040
color4 #375cd8
color12 #4250ef
color5 #ba35af
color13 #6052cf
color6 #1f6fbf
color14 #1477b2
color7 #e8e8ea
color15 #f5f5ff
