## author: Ryan Kaskel
## license: GNU GPLv3
## blurb: Powered by Protesilaos Stavrou's emacs themes

background #000000
foreground #d0d0d0
cursor #ff76ff
cursor_text_color #000000
url_color #3f95f6
active_border_color #857f8f
inactive_border_color #1a1a1a
bell_border_color #df8a5a
selection_foreground #000000
selection_background #d0d0d0
macos_titlebar_color background
color0 #000000
color8 #1a1a1a
color1 #ef6560
color9 #f47360
color2 #0faa26
color10 #6aad0f
color3 #bf9032
color11 #df8a5a
color4 #3f95f6
color12 #6a9fff
color5 #d369af
color13 #af85ff
color6 #4fbaef
color14 #1dbfcf
color7 #857f8f
color15 #d0d0d0
