## author: Ryan Kaskel
## license: GNU GPLv3
## blurb: Powered by Protesilaos Stavrou's emacs themes

background #fff5ea
foreground #584141
cursor #cf1f00
cursor_text_color #fff5ea
url_color #375cc6
active_border_color #63728f
inactive_border_color #f2e9db
bell_border_color #aa4f30
selection_foreground #fff5ea
selection_background #584141
macos_titlebar_color background
color0 #584141
color8 #63728f
color1 #ba2d2f
color9 #ce3f00
color2 #007a0a
color10 #5f7200
color3 #a45a22
color11 #aa4f30
color4 #375cc6
color12 #5f5fdf
color5 #ca3e54
color13 #8448aa
color6 #3f60af
color14 #0f7b8f
color7 #f2e9db
color15 #fff5ea
