## author: Ryan Kaskel
## license: GNU GPLv3
## blurb: Powered by Protesilaos Stavrou's emacs themes

background #f1ecd0
foreground #231a1f
cursor #774400
cursor_text_color #f1ecd0
url_color #113384
active_border_color #685f53
inactive_border_color #e4dbc0
bell_border_color #775228
selection_foreground #f1ecd0
selection_background #231a1f
macos_titlebar_color background
color0 #231a1f
color8 #685f53
color1 #882000
color9 #9a0000
color2 #226022
color10 #3a7800
color3 #6b4500
color11 #775228
color4 #113384
color12 #3a3da0
color5 #822478
color13 #50119f
color6 #125a7f
color14 #00676f
color7 #e4dbc0
color15 #f1ecd0
