## author: Ryan Kaskel
## license: GNU GPLv3
## blurb: Powered by Protesilaos Stavrou's emacs themes

background #edf5e2
foreground #221321
cursor #770080
cursor_text_color #edf5e2
url_color #375cc6
active_border_color #676470
inactive_border_color #e3e9d6
bell_border_color #88541f
selection_foreground #edf5e2
selection_background #221321
macos_titlebar_color background
color0 #221321
color8 #676470
color1 #c3303a
color9 #d00000
color2 #00601f
color10 #355500
color3 #9a501f
color11 #88541f
color4 #375cc6
color12 #444fcf
color5 #80308f
color13 #5032aa
color6 #1f70af
color14 #00677f
color7 #e3e9d6
color15 #edf5e2
