## author: Ryan Kaskel
## license: GNU GPLv3
## blurb: Powered by Protesilaos Stavrou's emacs themes

background #fcffff
foreground #232323
cursor #0055bb
cursor_text_color #fcffff
url_color #004fc0
active_border_color #66657f
inactive_border_color #eaefef
bell_border_color #996c4f
selection_foreground #fcffff
selection_background #232323
macos_titlebar_color background
color0 #232323
color8 #66657f
color1 #c42d2f
color9 #d03003
color2 #008a00
color10 #468400
color3 #aa6100
color11 #996c4f
color4 #004fc0
color12 #4244ef
color5 #aa44c5
color13 #7f5ae0
color6 #1f6fbf
color14 #007a85
color7 #eaefef
color15 #fcffff
