## author: Ryan Kaskel
## license: GNU GPLv3
## blurb: Powered by Protesilaos Stavrou's emacs themes

background #3b2043
foreground #e4d3e1
cursor #e0646a
cursor_text_color #3b2043
url_color #57aff6
active_border_color #9d9d9d
inactive_border_color #432e4e
bell_border_color #eec27f
selection_foreground #3b2043
selection_background #e4d3e1
macos_titlebar_color background
color0 #3b2043
color8 #432e4e
color1 #ef797f
color9 #ff7f5f
color2 #7fbb3f
color10 #aad05a
color3 #e4c53f
color11 #eec27f
color4 #57aff6
color12 #78b2ff
color5 #ffb2d6
color13 #afb1ff
color6 #5fc0dc
color14 #80dfbf
color7 #9d9d9d
color15 #e4d3e1
