## author: Ryan Kaskel
## license: GNU GPLv3
## blurb: Powered by Protesilaos Stavrou's emacs themes

background #fff7f7
foreground #201f36
cursor #d06f30
cursor_text_color #fff7f7
url_color #3c3bbe
active_border_color #776f79
inactive_border_color #efe7e7
bell_border_color #a04646
selection_foreground #fff7f7
selection_background #201f36
macos_titlebar_color background
color0 #201f36
color8 #776f79
color1 #b00234
color9 #e00033
color2 #217a3c
color10 #4a7d00
color3 #9a6012
color11 #a04646
color4 #3c3bbe
color12 #4250ef
color5 #a01f64
color13 #7022bf
color6 #2f5f9f
color14 #1077ab
color7 #efe7e7
color15 #fff7f7
