## author: Ryan Kaskel
## license: GNU GPLv3
## blurb: Powered by Protesilaos Stavrou's emacs themes

background #131c2b
foreground #eaedef
cursor #8fdfff
cursor_text_color #131c2b
url_color #57b0ff
active_border_color #969faf
inactive_border_color #1d2c39
bell_border_color #cab27f
selection_foreground #131c2b
selection_background #eaedef
macos_titlebar_color background
color0 #131c2b
color8 #1d2c39
color1 #ff6f6f
color9 #ff7a5f
color2 #41bf4f
color10 #7fce5f
color3 #d0d24f
color11 #cab27f
color4 #57b0ff
color12 #70a0ff
color5 #f59acf
color13 #cf90ff
color6 #2fd0db
color14 #65d5a8
color7 #969faf
color15 #eaedef
