## author: Ryan Kaskel
## license: GNU GPLv3
## blurb: Powered by Protesilaos Stavrou's emacs themes

background #352718
foreground #e8e4b1
cursor #f9cf7a
cursor_text_color #352718
url_color #57aff6
active_border_color #90918a
inactive_border_color #483426
bell_border_color #e7a06f
selection_foreground #352718
selection_background #e8e4b1
macos_titlebar_color background
color0 #352718
color8 #483426
color1 #ff7f7f
color9 #ff7f4f
color2 #6fd560
color10 #a0d13a
color3 #e4b53f
color11 #e7a06f
color4 #57aff6
color12 #98bfff
color5 #f0aac5
color13 #c6a2fe
color6 #6fcad0
color14 #70e0cf
color7 #90918a
color15 #e8e4b1
