## author: Ryan Kaskel
## license: GNU GPLv3
## blurb: Powered by Protesilaos Stavrou's emacs themes

background #edf4f8
foreground #151a27
cursor #036f99
cursor_text_color #edf4f8
url_color #375cc6
active_border_color #676470
inactive_border_color #e0e7ef
bell_border_color #78542f
selection_foreground #edf4f8
selection_background #151a27
macos_titlebar_color background
color0 #151a27
color8 #676470
color1 #c3303a
color9 #d00000
color2 #007010
color10 #3a6f00
color3 #805a1f
color11 #78542f
color4 #375cc6
color12 #444fcf
color5 #80308f
color13 #5f2fba
color6 #1f66af
color14 #006f70
color7 #e0e7ef
color15 #edf4f8
