## author: Ryan Kaskel
## license: GNU GPLv3
## blurb: Powered by Protesilaos Stavrou's emacs themes

background #292c2f
foreground #d0d0d0
cursor #afe6ef
cursor_text_color #292c2f
url_color #80a4e0
active_border_color #857f8f
inactive_border_color #373b3d
bell_border_color #cf9f90
selection_foreground #292c2f
selection_background #d0d0d0
macos_titlebar_color background
color0 #292c2f
color8 #373b3d
color1 #d67869
color9 #df885f
color2 #70bb70
color10 #98c06f
color3 #c09f6f
color11 #cf9f90
color4 #80a4e0
color12 #a0a0ef
color5 #e5a0ea
color13 #cfa0e8
color6 #8fb8ea
color14 #7ac0b9
color7 #857f8f
color15 #d0d0d0
