## author: Ryan Kaskel
## license: GNU GPLv3
## blurb: Powered by Protesilaos Stavrou's emacs themes

background #322023
foreground #e4d3e1
cursor #ef607a
cursor_text_color #322023
url_color #57aff6
active_border_color #9d9d9d
inactive_border_color #432e32
bell_border_color #eec26f
selection_foreground #322023
selection_background #e4d3e1
macos_titlebar_color background
color0 #322023
color8 #432e32
color1 #ff707f
color9 #ff7f5f
color2 #5fbb5f
color10 #8ad05a
color3 #e4c53f
color11 #eec26f
color4 #57aff6
color12 #78b2ff
color5 #ffb2d6
color13 #cfb1ff
color6 #5fc0dc
color14 #80dfbf
color7 #9d9d9d
color15 #e4d3e1
