## author: Ryan Kaskel
## license: GNU GPLv3
## blurb: Powered by Protesilaos Stavrou's emacs themes

background #130911
foreground #d0d0d0
cursor #f0af7f
cursor_text_color #130911
url_color #3f95f6
active_border_color #857f8f
inactive_border_color #221920
bell_border_color #df8a5a
selection_foreground #130911
selection_background #d0d0d0
macos_titlebar_color background
color0 #130911
color8 #221920
color1 #ef6360
color9 #ff7355
color2 #0faa26
color10 #6aad0f
color3 #bf9032
color11 #df8a5a
color4 #3f95f6
color12 #6a9fff
color5 #d369af
color13 #af85ff
color6 #4fbaef
color14 #1dbfcf
color7 #857f8f
color15 #d0d0d0
