## author: Ryan Kaskel
## license: GNU GPLv3
## blurb: Powered by Protesilaos Stavrou's emacs themes

background #fff2f3
foreground #4f4073
cursor #cf0090
cursor_text_color #fff2f3
url_color #375ce6
active_border_color #786e74
inactive_border_color #f2e4ea
bell_border_color #b65050
selection_foreground #fff2f3
selection_background #4f4073
macos_titlebar_color background
color0 #4f4073
color8 #786e74
color1 #d3303a
color9 #e00033
color2 #217a3c
color10 #4a7d00
color3 #a45f22
color11 #b65050
color4 #375ce6
color12 #5250ef
color5 #ba35af
color13 #8e44f3
color6 #1f6fbf
color14 #0f7b8f
color7 #f2e4ea
color15 #fff2f3
