## author: Ryan Kaskel
## license: GNU GPLv3
## blurb: Powered by Protesilaos Stavrou's emacs themes

background #f6fff9
foreground #34494a
cursor #bf005f
cursor_text_color #f6fff9
url_color #375cc6
active_border_color #777294
inactive_border_color #e8f0f0
bell_border_color #ae5a30
selection_foreground #f6fff9
selection_background #34494a
macos_titlebar_color background
color0 #34494a
color8 #777294
color1 #c42d2f
color9 #d03003
color2 #1a870f
color10 #4a7d00
color3 #a45f22
color11 #ae5a30
color4 #375cc6
color12 #5f5fdf
color5 #d5206f
color13 #9435b4
color6 #1f6fbf
color14 #0f7b8f
color7 #e8f0f0
color15 #f6fff9
