## author: Ryan Kaskel
## license: GNU GPLv3
## blurb: Powered by Protesilaos Stavrou's emacs themes

background #160f0f
foreground #d8cfd5
cursor #ff99ff
cursor_text_color #160f0f
url_color #7fa5f6
active_border_color #908890
inactive_border_color #2a2228
bell_border_color #ef9680
selection_foreground #160f0f
selection_background #d8cfd5
macos_titlebar_color background
color0 #160f0f
color8 #2a2228
color1 #f48359
color9 #ff7560
color2 #60b444
color10 #a0c27f
color3 #d4a052
color11 #ef9680
color4 #7fa5f6
color12 #8895ff
color5 #d37faf
color13 #a698ef
color6 #8fbaff
color14 #8fcfdf
color7 #908890
color15 #d8cfd5
