## author: Ryan Kaskel
## license: GNU GPLv3
## blurb: Powered by Protesilaos Stavrou's emacs themes

background #fff9f9
foreground #1a1a1a
cursor #bb0000
cursor_text_color #fff9f9
url_color #375cd8
active_border_color #756275
inactive_border_color #efecec
bell_border_color #765040
selection_foreground #fff9f9
selection_background #1a1a1a
macos_titlebar_color background
color0 #1a1a1a
color8 #756275
color1 #aa0010
color9 #dd0000
color2 #217a3c
color10 #4a7d00
color3 #805d00
color11 #765040
color4 #375cd8
color12 #4250ef
color5 #aa357f
color13 #af40af
color6 #2070af
color14 #007faa
color7 #efecec
color15 #fff9f9
