## author: Ryan Kaskel
## license: GNU GPLv3
## blurb: Powered by Protesilaos Stavrou's emacs themes

background #f8f5ff
foreground #4f3363
cursor #4f45ff
cursor_text_color #f8f5ff
url_color #375cd6
active_border_color #786e74
inactive_border_color #ebe7f1
bell_border_color #b65050
selection_foreground #f8f5ff
selection_background #4f3363
macos_titlebar_color background
color0 #4f3363
color8 #786e74
color1 #c3303a
color9 #d03033
color2 #057800
color10 #4f7d0f
color3 #a45f22
color11 #b65050
color4 #375cd6
color12 #5165e4
color5 #ad45ba
color13 #705ae3
color6 #1f6fbf
color14 #0f7a9d
color7 #ebe7f1
color15 #f8f5ff
