## author: Ryan Kaskel
## license: GNU GPLv3
## blurb: Powered by Protesilaos Stavrou's emacs themes

background #0f0b15
foreground #b8c6d5
cursor #ff6ff0
cursor_text_color #0f0b15
url_color #3f95f6
active_border_color #807c9f
inactive_border_color #1d202f
bell_border_color #df9080
selection_foreground #0f0b15
selection_background #b8c6d5
macos_titlebar_color background
color0 #0f0b15
color8 #1d202f
color1 #f47359
color9 #ef6560
color2 #29a444
color10 #6aad0f
color3 #b58a52
color11 #df9080
color4 #3f95f6
color12 #6a9fff
color5 #d369af
color13 #af85ea
color6 #4fbaef
color14 #35afbf
color7 #807c9f
color15 #b8c6d5
