## author: Ryan Kaskel
## license: GNU GPLv3
## blurb: Powered by Protesilaos Stavrou's emacs themes

background #000000
foreground #ffffff
cursor #efef00
cursor_text_color #000000
url_color #2fafff
active_border_color #989898
inactive_border_color #1e1e1e
bell_border_color #d8af7a
selection_foreground #000000
selection_background #ffffff
macos_titlebar_color background
color0 #000000
color8 #1e1e1e
color1 #ff5f59
color9 #ff6b55
color2 #44bc44
color10 #70b900
color3 #cabf00
color11 #d8af7a
color4 #2fafff
color12 #79a8ff
color5 #feacd0
color13 #b6a0ff
color6 #00d3d0
color14 #6ae4b9
color7 #989898
color15 #ffffff
