## author: Ryan Kaskel
## license: GNU GPLv3
## blurb: Powered by Protesilaos Stavrou's emacs themes

background #fbf7f0
foreground #000000
cursor #d00000
cursor_text_color #fbf7f0
url_color #0031a9
active_border_color #595959
inactive_border_color #efe9dd
bell_border_color #602938
selection_foreground #fbf7f0
selection_background #000000
macos_titlebar_color background
color0 #000000
color8 #595959
color1 #a60000
color9 #972500
color2 #006300
color10 #306010
color3 #6d5000
color11 #602938
color4 #0031a9
color12 #3546c2
color5 #721045
color13 #531ab6
color6 #00598b
color14 #005f5f
color7 #efe9dd
color15 #fbf7f0
