## author: Ryan Kaskel
## license: GNU GPLv3
## blurb: Powered by Protesilaos Stavrou's emacs themes

background #ffffff
foreground #000000
cursor #0000ff
cursor_text_color #ffffff
url_color #0031a9
active_border_color #595959
inactive_border_color #f2f2f2
bell_border_color #77492f
selection_foreground #ffffff
selection_background #000000
macos_titlebar_color background
color0 #000000
color8 #595959
color1 #a60000
color9 #972500
color2 #006800
color10 #316500
color3 #695500
color11 #77492f
color4 #0031a9
color12 #3548cf
color5 #721045
color13 #531ab6
color6 #005e8b
color14 #005f5f
color7 #f2f2f2
color15 #ffffff
