## author: Ryan Kaskel
## license: GNU GPLv3
## blurb: Powered by Protesilaos Stavrou's emacs themes

background #0d0e1c
foreground #ffffff
cursor #ff66ff
cursor_text_color #0d0e1c
url_color #2fafff
active_border_color #989898
inactive_border_color #1d2235
bell_border_color #dfaf7a
selection_foreground #0d0e1c
selection_background #ffffff
macos_titlebar_color background
color0 #0d0e1c
color8 #1d2235
color1 #ff5f59
color9 #ff6b55
color2 #44bc44
color10 #75c13e
color3 #d0bc00
color11 #dfaf7a
color4 #2fafff
color12 #79a8ff
color5 #feacd0
color13 #b6a0ff
color6 #00d3d0
color14 #6ae4b9
color7 #989898
color15 #ffffff
