[aws]
disabled = true

[battery]
disabled = true

[docker_context]
disabled = true

[gcloud]
disabled = true

[hg_branch]
disabled = true

[java]
disabled = true

[openstack]
disabled = true

[package]
disabled = true

[python]
symbol = "󰌠 "
