update
upgrade

install git
install emacs --cocoa --srgb --with-gnutls
install coreutils
install findutils
install bash
install tmux
install ack
install python
install python3
install bash-completion
install node
install chruby
install ruby-install
install leiningen
install postgres
install tree
install redis
install aspell --with-lang-en --with-lang-pl
install lua
install couchdb
install htop-osx
install hub
install tarsnap
install haskell-platform
install git-flow
install curl-ca-bundle
install go
install dnsmasq
install zsh
install reattach-to-user-namespace
install libyaml
install fasd

cleanup
