#!/usr/bin/env zsh

DOTEMACS_DIR=${0:a:h}
STRAIGHT_REPO_DIR="${DOTEMACS_DIR}/straight/repos"

for dir in $STRAIGHT_REPO_DIR/*/; do
  if [[ ! -d ./.git ]]; then
    continue
  fi
  behind=$(git -C $dir rev-list HEAD..origin --count)
  if (( behind > 0 )); then
    echo "${dir:t}: ${behind}"
  fi
done
